# Generated by Django 5.0.3 on 2024-05-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_room_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
