# Generated by Django 5.0.3 on 2024-05-16 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0004_room_receiver_name_room_sender_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.IntegerField(),
        ),
    ]
