# Generated by Django 5.0.3 on 2024-05-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0005_remove_room_receiver_name_remove_room_sender_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.room'),
        ),
    ]
