# Generated by Django 5.0.3 on 2024-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0006_alter_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
