# Generated by Django 5.0.3 on 2024-05-27 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0007_remove_room_id_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
