# Generated by Django 5.0.3 on 2024-03-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/posts/%Y/%m/%d/'),
        ),
    ]
