# Generated by Django 5.0.3 on 2024-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_seguidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/photo_profile/'),
        ),
    ]
