# Generated by Django 5.0.3 on 2024-06-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_post_curtidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='curtidas',
        ),
        migrations.AddField(
            model_name='user',
            name='posts_likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_likes', to='user.post'),
        ),
    ]
